# Generated by Django 4.1.5 on 2023-05-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_podaci_email_alter_podaci_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podaci',
            name='description',
        ),
        migrations.RemoveField(
            model_name='podaci',
            name='email',
        ),
        migrations.RemoveField(
            model_name='podaci',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='podaci',
            name='name',
        ),
        migrations.RemoveField(
            model_name='podaci',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='podaci',
            name='price',
        ),
    ]
