# Generated by Django 4.1.5 on 2023-05-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_podaci_description_remove_podaci_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podaci',
            name='image',
        ),
        migrations.AddField(
            model_name='podaci',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='podaci',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
