# Generated by Django 4.1.5 on 2023-05-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_podaci_image_podaci_email_podaci_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='podaci',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='podaci',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='podaci',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
