# Generated by Django 4.1.5 on 2023-05-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_podaci_description_podaci_klass_podaci_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaci',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='podaci',
            name='klass',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='podaci',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='podaci',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
