# Generated by Django 4.1.5 on 2023-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_podaci_description_alter_podaci_klass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podaci',
            name='product',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
