# Generated by Django 4.1.5 on 2023-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_podaci_price_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaci',
            name='price_kg',
            field=models.CharField(max_length=10),
        ),
    ]
