# Generated by Django 4.1.5 on 2023-05-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_podaci_price_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podaci',
            name='price_kg',
        ),
    ]
