# Generated by Django 4.1.5 on 2023-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_podaci_price_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaci',
            name='product',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
